server.port=8080
spring.application.name=consistent-hashing-lab

# We do NOT let Spring Boot auto-connect to a single Mongo instance.
# Instead we read this comma separated list ourselves in MongoNodeConfig
# and open one MongoTemplate per node. Format = name:host:port
storage.nodes=node1:localhost:27017,node2:localhost:27018,node3:localhost:27019
storage.database=studentdb
storage.virtualNodesPerNode=3
