spring.application.name=rate-limiter

# Redis connection (Memurai on Windows, or native Redis on Linux/Mac)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Token Bucket configuration
rate.limiter.bucket-capacity=10
rate.limiter.refill-interval-millis=1000
rate.limiter.refill-amount=1

server.port=8080
