services:

  redis:
    image: redis:7-alpine
    container_name: crawler-redis
    ports:
      - "6379:6379"

  crawler:
    build: .
    container_name: web-crawler
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis